name: 'Publish'
on:
  release:
    types: # This configuration does not affect the page_build event above
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile
      - run: yarn test

      - id: publish-release
        if: '!github.event.release.prerelease'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          check-version: true
          tag: 'latest'
      - if: steps.publish-release.outputs.type != 'none'
        run: |
          echo "Published latest release. Version changed: ${{ steps.publish-release.outputs.old-version }} => ${{ steps.publish-release.outputs.version }}"

      - id: publish-prerelease
        if: 'github.event.release.prerelease'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          check-version: true
          tag: 'next'
      - if: steps.publish-prerelease.outputs.type != 'none'
        run: |
          echo "Published latest prerelease. Version changed: ${{ steps.publish-prerelease.outputs.old-version }} => ${{ steps.publish-prerelease.outputs.version }}"
